[phases.build]
cmds = ["pip install -r requirements.txt", "python manage.py collectstatic --noinput"]

[start]
cmd = "python manage.py migrate && python manage.py ensure_superuser && gunicorn core.wsgi --bind 0.0.0.0:$PORT --workers 2"
