# Generated by Django 6.0.6 on 2026-07-19 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sandboxprogram',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
