# Generated by Django 6.0.6 on 2026-06-24 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_lessonquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonquestion',
            name='choices',
            field=models.TextField(blank=True, default='', help_text='One choice per line (multiple choice only)'),
        ),
        migrations.AddField(
            model_name='lessonquestion',
            name='question_type',
            field=models.CharField(choices=[('output', 'Paste Output'), ('short_answer', 'Short Answer'), ('true_false', 'True / False'), ('multiple_choice', 'Multiple Choice')], default='output', max_length=20),
        ),
    ]
