# Generated by Django 6.0.6 on 2026-06-24 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_add_assignment_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='test_inputs',
            field=models.TextField(blank=True, default='', help_text='One input value per line, in the order they will be fed to input() calls when the code runs.'),
        ),
    ]
